global:
  scrape_interval: 5s # How often to grab metrics from your app (5 seconds)

scrape_configs:
  - job_name: "api-gateway"
    static_configs:
      - targets: ["api-gateway:8000"] # Points directly to your FastAPI container